export const POKEMON_ABILITIES = [
	'Grass Pelt',
	'Cloud Nine',
	'Synchronize',
	'Flare Boost',
	'Tangling Hair',
	'Multitype',
	'Snow Cloak',
	'Filter',
	'Minus',
	'Clear Body',
	'Moxie',
	'Wonder Guard',
	'Sand Veil',
	'Illuminate',
	'Prankster',
	'Weak Armor',
	'Simple',
	'Damp',
	'Sand Rush',
	'Shell Armor',
	'Own Tempo',
	'Dark Aura',
	'Defeatist',
	'Grassy Surge',
	'Poison Touch',
	'Pickpocket',
	'Run Away',
	'Flower Veil',
	'Imposter',
	'Rivalry',
	'Gooey',
	'Bad Dreams',
	'Swarm',
	'Hustle',
	'Leaf Guard',
	'Early Bird',
	'Power of Alchemy',
	'Compoundeyes',
	'Disguise',
	'Solar Power',
	'Dry Skin',
	'Natural Cure',
	'Rough Skin',
	'Emergency Exit',
	'Teravolt',
	'Queenly Majesty',
	'Aftermath',
	'Huge Power',
	'Heatproof',
	'Technician',
	'RKS System',
	'Regenerator',
	'Protean',
	'Light Metal',
	'Slush Rush',
	'Refrigerate',
	'Justified',
	'Battle Bond',
	'Shadow Shield',
	'Merciless',
	'Big Pecks',
	'Toxic Boost',
	'Shield Dust',
	'Soul-Heart',
	'No Guard',
	'Flash Fire',
	'Scrappy',
	'Fluffy',
	'Poison Point',
	'Frisk',
	'Anticipation',
	'Unburden',
	'Fairy Aura',
	'Dancer',
	'Mold Breaker',
	'Air Lock',
	'White Smoke',
	'Liquid Voice',
	'Intimidate',
	'Rain Dish',
	'Magic Guard',
	'Aura Break',
	'Rattled',
	'Poison Heal',
	'Wonder Skin ',
	'Multiscale',
	'Harvest',
	'Overgrow',
	'Stench',
	'Beast Boost',
	'Snow Warning',
	'Rock Head',
	'Pure Power',
	'Symbiosis',
	'Pixilate',
	'Color Change',
	'Swift Swim',
	'Truant',
	'Heavy Metal',
	'Thick Fat',
	'Overcoat',
	'Slow Start',
	'Iron Barbs',
	'Zen Mode',
	'Water Compaction',
	'Defiant',
	'Strong Jaw',
	'Infiltrator',
	'Super Luck',
	'Triage',
	'Static',
	'Healer',
	'Corrosion',
	'Oblivious',
	'Magma Armor',
	'Receiver',
	'Cursed Body',
	'Reckless',
	'Motor Drive',
	'Mega Launcher',
	'Wimp Out',
	'Guts',
	'Competitive',
	'Stance Change',
	'Water Absorb',
	'Berserk',
	'Flame Body',
	'Comatose',
	'Drought',
	'Mummy',
	'Drizzle',
	'Inner Focus',
	'Analytic',
	'Shields Down',
	'Sturdy',
	'Stamina',
	'Sniper',
	'Stakeout',
	'Arena Trap',
	'Steelworker',
	'Soundproof',
	'Storm Drain',
	'Download',
	'Friend Guard',
	'Vital Spirit',
	'Unnerve',
	'Water Veil',
	'Blaze',
	'Fur Coat',
	'Hydration',
	'Flower Gift',
	'Magician',
	'Illusion',
	'Ice Body',
	'Limber',
	'Adaptability',
	'Telepathy',
	'Klutz',
	'Tangled Feet',
	'Victory Star',
	'Sand Force',
	'Volt Absorb',
	'Turboblaze',
	'Cute Charm',
	'Keen Eye',
	'Marvel Scale',
	'Contrary',
	'Sweet Veil',
	'Pickup',
	'Battle Armor',
	'Serene Grace',
	'Electric Surge',
	'Prism Armor',
	'Long Reach',
	'Stall',
	'Full Metal Body',
	'Dazzling',
	'Liquid Ooze',
	'Power Construct',
	'Pressure',
	'Normalize',
	'Effect Spore',
	'Moody',
	'Water Bubble',
	'Aroma Veil',
	'Psychic Surge',
	'Plus',
	'Chlorophyll',
	'Innards Out',
	'Gale Wings',
	'Tinted Lens',
	'Trace',
	'Forecast',
	'Unaware',
	'Shed Skin',
	'Honey Gather',
	'Tough Claws',
	'Steadfast',
	'Insomnia',
	'Schooling',
	'Sheer Force',
	'Shadow Tag',
	'Suction Cups',
	'Iron Fist',
	'Lightningrod',
	'Magnet Pull',
	'Forewarn',
	'Sap Sipper',
	'Gluttony',
	'Solid Rock',
	'Magic Bounce',
	'Misty Surge',
	'Sand Stream',
	'Bulletproof',
	'Galvanize',
	'Torrent',
	'Anger Point',
	'Battery',
	'Cheek Pouch',
	'Speed Boost',
	'Levitate',
	'Immunity',
	'Sticky Hold',
	'Surge Surfer',
	'Skill Link',
	'Quick Feet',
	'Hyper Cutter',
];
